### ISSUE TITLE
Missing Verde import before creating grid coordinates

### ISSUE THREAD

**Issue by leouieda** [agile-geoscience/xlines#5]
@kwinkunks the code for creating the coordinates is using verde before importing it. Should I change this back to using `mgrid` like in the blog post? `Spline.grid` doesn't actually need these arrays as it generates them internally. I like the `verde.grid_coordinates` function because it deals with the tricky situation of grid spacings not being a multiple of the desired grid extent. There are sorts of corner cases that it has to deal with (see http://www.fatiando.org/verde/dev/api/generated/verde.grid_coordinates.html).

**Comment by kwinkunks** [comment]
Right, sorry about that... I guess I like the idea of sticking to fairly 'core' libraries, at least in these more generic tutorials. I'll explore Verde and I think we'll do another for it specifically.

**Comment by kwinkunks** [comment]
Fixed in 89b7493300d45905df15302de45539111ea2631d

**Comment by leouieda** [comment]
:+1: no problem
